import type {
  Employee,
  AttendanceRecord,
  PayslipData,
  LeaveBalance,
  LeaveRequest,
  AuditLog,
  JobPosting,
} from "./types"

export const CURRENT_USER = {
  name: "Alex Johnson",
  initials: "AJ",
  title: "UX Designer L2",
  department: "Engineering",
  employeeId: "EMP-2847",
  email: "alex.johnson@workos.io",
  phone: "+63 917 123 4567",
  address: "Makati City, Metro Manila",
  startDate: "March 15, 2022",
  manager: "Maria Santos",
  team: "Product Design",
}

export const leaveBalances: LeaveBalance[] = [
  { type: "Vacation Leave", total: 15, used: 7, remaining: 8, color: "green" },
  { type: "Sick Leave", total: 15, used: 4, remaining: 11, color: "blue" },
  { type: "Emergency Leave", total: 5, used: 2, remaining: 3, color: "amber" },
  { type: "Special Leave", total: 3, used: 0, remaining: 3, color: "purple" },
]

export const attendanceRecords: AttendanceRecord[] = [
  {
    date: "Apr 1",
    day: "Tue",
    timeIn: "8:58 AM",
    timeOut: "6:05 PM",
    hoursWorked: "9h 07m",
    otHours: "1.1",
    status: "present",
  },
  {
    date: "Mar 31",
    day: "Mon",
    timeIn: "9:02 AM",
    timeOut: "6:00 PM",
    hoursWorked: "8h 58m",
    otHours: "—",
    status: "present",
  },
  {
    date: "Mar 28",
    day: "Fri",
    timeIn: "9:15 AM",
    timeOut: "6:00 PM",
    hoursWorked: "8h 45m",
    otHours: "—",
    status: "late",
  },
  {
    date: "Mar 27",
    day: "Thu",
    timeIn: "8:45 AM",
    timeOut: "8:30 PM",
    hoursWorked: "11h 45m",
    otHours: "2.5",
    status: "present",
  },
  {
    date: "Mar 26",
    day: "Wed",
    timeIn: "8:55 AM",
    timeOut: "6:00 PM",
    hoursWorked: "9h 05m",
    otHours: "—",
    status: "present",
  },
  {
    date: "Mar 25",
    day: "Tue",
    timeIn: "—",
    timeOut: "—",
    hoursWorked: "—",
    otHours: "—",
    status: "leave",
  },
  {
    date: "Mar 24",
    day: "Mon",
    timeIn: "—",
    timeOut: "—",
    hoursWorked: "—",
    otHours: "—",
    status: "leave",
  },
  {
    date: "Mar 22",
    day: "Sat",
    timeIn: "—",
    timeOut: "—",
    hoursWorked: "—",
    otHours: "—",
    status: "restday",
  },
  {
    date: "Mar 21",
    day: "Fri",
    timeIn: "8:50 AM",
    timeOut: "6:00 PM",
    hoursWorked: "9h 10m",
    otHours: "—",
    status: "present",
  },
  {
    date: "Mar 20",
    day: "Thu",
    timeIn: "9:00 AM",
    timeOut: "6:00 PM",
    hoursWorked: "9h 00m",
    otHours: "—",
    status: "present",
  },
]

export const payslips: PayslipData[] = [
  {
    period: "June 2025",
    basic: "₱45,000.00",
    otHrs: "—",
    ot: "—",
    gross: "₱45,000.00",
    sss: "—",
    philhealth: "—",
    pagibig: "—",
    tax: "—",
    deductions: "—",
    net: "—",
    released: "Jun 30",
    status: "upcoming",
  },
  {
    period: "May 2025",
    basic: "₱45,000.00",
    otHrs: "12.5",
    ot: "₱3,375.00",
    gross: "₱48,375.00",
    sss: "₱1,125.00",
    philhealth: "₱900.00",
    pagibig: "₱200.00",
    tax: "₱3,575.00",
    deductions: "₱5,800.00",
    net: "₱42,575.00",
    released: "May 30",
    status: "released",
  },
  {
    period: "April 2025",
    basic: "₱45,000.00",
    otHrs: "7.5",
    ot: "₱1,800.00",
    gross: "₱46,800.00",
    sss: "₱1,125.00",
    philhealth: "₱900.00",
    pagibig: "₱200.00",
    tax: "₱2,575.00",
    deductions: "₱4,800.00",
    net: "₱42,000.00",
    released: "Apr 30",
    status: "released",
  },
  {
    period: "March 2025",
    basic: "₱45,000.00",
    otHrs: "—",
    ot: "—",
    gross: "₱45,000.00",
    sss: "₱1,125.00",
    philhealth: "₱900.00",
    pagibig: "₱200.00",
    tax: "₱3,575.00",
    deductions: "₱5,800.00",
    net: "₱39,200.00",
    released: "Mar 31",
    status: "released",
  },
  {
    period: "February 2025",
    basic: "₱45,000.00",
    otHrs: "9.375",
    ot: "₱2,250.00",
    gross: "₱47,250.00",
    sss: "₱1,125.00",
    philhealth: "₱900.00",
    pagibig: "₱200.00",
    tax: "₱3,575.00",
    deductions: "₱5,800.00",
    net: "₱41,450.00",
    released: "Feb 28",
    status: "released",
  },
  {
    period: "January 2025",
    basic: "₱45,000.00",
    otHrs: "3.75",
    ot: "₱900.00",
    gross: "₱45,900.00",
    sss: "₱1,125.00",
    philhealth: "₱900.00",
    pagibig: "₱200.00",
    tax: "₱3,575.00",
    deductions: "₱5,800.00",
    net: "₱40,100.00",
    released: "Jan 31",
    status: "released",
  },
]

export const employees: Employee[] = [
  {
    id: "EMP-2847",
    name: "Alex Johnson",
    initials: "AJ",
    email: "alex.johnson@workos.io",
    department: "Engineering",
    position: "UX Designer L2",
    role: "employee",
    status: "active",
    startDate: "Mar 15, 2022",
    employeeId: "EMP-2847",
  },
  {
    id: "EMP-1923",
    name: "Sofia Martinez",
    initials: "SM",
    email: "sofia.martinez@workos.io",
    department: "Engineering",
    position: "Senior Frontend Engineer",
    role: "employee",
    status: "active",
    startDate: "Jan 10, 2021",
    employeeId: "EMP-1923",
  },
  {
    id: "EMP-3041",
    name: "James Wu",
    initials: "JW",
    email: "james.wu@workos.io",
    department: "Design",
    position: "Product Designer",
    role: "employee",
    status: "on-leave",
    startDate: "Jul 22, 2023",
    employeeId: "EMP-3041",
  },
  {
    id: "EMP-2215",
    name: "Priya Sharma",
    initials: "PS",
    email: "priya.sharma@workos.io",
    department: "Sales",
    position: "Account Executive",
    role: "employee",
    status: "active",
    startDate: "Sep 5, 2022",
    employeeId: "EMP-2215",
  },
  {
    id: "EMP-1102",
    name: "Daniel Kim",
    initials: "DK",
    email: "daniel.kim@workos.io",
    department: "Engineering",
    position: "Backend Engineer L3",
    role: "employee",
    status: "active",
    startDate: "Feb 14, 2020",
    employeeId: "EMP-1102",
  },
  {
    id: "EMP-3381",
    name: "Aisha Okafor",
    initials: "AO",
    email: "aisha.okafor@workos.io",
    department: "People Ops",
    position: "HR Coordinator",
    role: "hr",
    status: "active",
    startDate: "Oct 1, 2023",
    employeeId: "EMP-3381",
  },
]

export const leaveRequests: LeaveRequest[] = [
  {
    id: "LR-0041",
    employee: "Alex Johnson",
    initials: "AJ",
    type: "Vacation Leave",
    from: "Jun 14, 2025",
    to: "Jun 16, 2025",
    days: 3,
    status: "pending",
    reason: "Family trip",
    filed: "Apr 1, 2025",
  },
  {
    id: "LR-0039",
    employee: "James Wu",
    initials: "JW",
    type: "Sick Leave",
    from: "Mar 25, 2025",
    to: "Mar 26, 2025",
    days: 2,
    status: "approved",
    reason: "Medical appointment",
    filed: "Mar 24, 2025",
  },
  {
    id: "LR-0037",
    employee: "Sofia Martinez",
    initials: "SM",
    type: "Emergency Leave",
    from: "Mar 20, 2025",
    to: "Mar 20, 2025",
    days: 1,
    status: "approved",
    reason: "Family emergency",
    filed: "Mar 19, 2025",
  },
  {
    id: "LR-0035",
    employee: "Priya Sharma",
    initials: "PS",
    type: "Vacation Leave",
    from: "Apr 5, 2025",
    to: "Apr 7, 2025",
    days: 3,
    status: "pending",
    reason: "Personal travel",
    filed: "Apr 1, 2025",
  },
  {
    id: "LR-0033",
    employee: "Daniel Kim",
    initials: "DK",
    type: "Sick Leave",
    from: "Apr 3, 2025",
    to: "Apr 4, 2025",
    days: 2,
    status: "pending",
    reason: "Flu / fever",
    filed: "Apr 2, 2025",
  },
]

export const auditLogs: AuditLog[] = [
  {
    id: "AU-8841",
    user: "Robert Chen",
    initials: "RC",
    action: "Role updated",
    target: "EMP-2847 → HR access granted",
    ip: "192.168.1.42",
    timestamp: "Apr 1, 2025 · 10:14 AM",
    severity: "warning",
  },
  {
    id: "AU-8840",
    user: "Maria Santos",
    initials: "MS",
    action: "Payroll released",
    target: "March 2025 · 48 employees",
    ip: "10.0.0.15",
    timestamp: "Apr 1, 2025 · 9:02 AM",
    severity: "info",
  },
  {
    id: "AU-8839",
    user: "Robert Chen",
    initials: "RC",
    action: "Config changed",
    target: "Overtime multiplier 1.25 → 1.30",
    ip: "192.168.1.42",
    timestamp: "Mar 31, 2025 · 5:47 PM",
    severity: "critical",
  },
  {
    id: "AU-8838",
    user: "Maria Santos",
    initials: "MS",
    action: "Leave approved",
    target: "LR-0039 · James Wu · 2 days",
    ip: "10.0.0.15",
    timestamp: "Mar 31, 2025 · 3:30 PM",
    severity: "info",
  },
  {
    id: "AU-8837",
    user: "System",
    initials: "SY",
    action: "Backup completed",
    target: "Database snapshot · 2.4 GB",
    ip: "—",
    timestamp: "Mar 31, 2025 · 2:00 AM",
    severity: "info",
  },
]

export const jobPostings: JobPosting[] = [
  {
    id: "JOB-014",
    title: "Senior Frontend Engineer",
    department: "Engineering",
    location: "Remote",
    type: "Full-time",
    salary: "$140–180k",
    status: "new",
    applications: 12,
    tags: ["React", "TypeScript"],
  },
  {
    id: "JOB-013",
    title: "Product Designer",
    department: "Design",
    location: "NYC / Remote",
    type: "Full-time",
    salary: "$120–150k",
    status: "urgent",
    applications: 7,
    tags: ["Figma", "Systems"],
  },
  {
    id: "JOB-012",
    title: "HR Business Partner",
    department: "People Ops",
    location: "Hybrid",
    type: "Full-time",
    salary: "$90–120k",
    status: "open",
    applications: 21,
    tags: [],
  },
  {
    id: "JOB-011",
    title: "Backend Engineer L3",
    department: "Engineering",
    location: "Remote",
    type: "Full-time",
    salary: "$130–160k",
    status: "open",
    applications: 34,
    tags: ["Go", "PostgreSQL"],
  },
]
